### ISSUE TITLE
Unable to initialize livequery connect

### ISSUE THREAD

**Issue by shankarnat** [TGIO/ParseLiveQuery#12]
https://github.com/shankarnat/ParseLive-Query - is my code.  I had tried to do the same example as given in your repository.
Also, I used this backend for just Parse to Insert and read; it worked. 

This is the example of the code with just Parse (and not live query against the same backend_ https://github.com/shankarnat/ParseExample and this works and ingests the data.
Now, I confused as to what I am missing. 
I have updated the index.js file to ensure the API call and livequery parameters are added as per - this https://github.com/ParsePlatform/parse-server-example/blob/master/index.js  and the websocket for the backend is also enabled. 
Can you help?

11-26 02:50:30.024 21173-21173/com.example.shankan.querylive_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.example.shankan.querylive_example, PID: 21173
                                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.parse.ParsePlugins.getParseDir()' on a null object reference
                                                                                           at com.parse.Parse.getParseDir(Parse.java:516)
                                                                                           at com.parse.ParseCorePlugins.getCurrentUserController(ParseCorePlugins.java:130)
                                                                                           at com.parse.ParseUser.getCurrentUserController(ParseUser.java:55)
                                                                                           at com.parse.ParseUser.getCurrentUserAsync(ParseUser.java:883)
                                                                                           at com.parse.ParseObject.saveInBackground(ParseObject.java:1405)
                                                                                           at com.example.shankan.querylive_example.MainActivity$7.onClick(MainActivity.java:138)
                                                                                           at android.view.View.performClick(View.java:5198)
                                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 02:51:07.743 21675-21675/com.example.shankan.querylive_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.example.shankan.querylive_example, PID: 21675
                                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.parse.ParsePlugins.getParseDir()' on a null object reference
                                                                                           at com.parse.Parse.getParseDir(Parse.java:516)
                                                                                           at com.parse.ParseCorePlugins.getCurrentUserController(ParseCorePlugins.java:130)
                                                                                           at com.parse.ParseUser.getCurrentUserController(ParseUser.java:55)
                                                                                           at com.parse.ParseUser.getCurrentUserAsync(ParseUser.java:883)
                                                                                           at com.parse.ParseObject.saveInBackground(ParseObject.java:1405)
                                                                                           at com.example.shankan.querylive_example.MainActivity$7.onClick(MainActivity.java:138)
                                                                                           at android.view.View.performClick(View.java:5198)
                                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 02:54:00.050 21914-21914/com.example.shankan.querylive_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.example.shankan.querylive_example, PID: 21914
                                                                                       java.lang.NullPointerException: url == null
                                                                                           at okhttp3.Request$Builder.url(Request.java:131)
                                                                                           at tgio.parselivequery.LiveQueryClient.connectToServer(LiveQueryClient.java:63)
                                                                                           at tgio.parselivequery.LiveQueryClient.connect(LiveQueryClient.java:105)
                                                                                           at com.example.shankan.querylive_example.MainActivity$5.onClick(MainActivity.java:117)
                                                                                           at android.view.View.performClick(View.java:5198)
                                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by TGIO** [comment]
Did library work with server example provided ?
